server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
ribbon:
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule